apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql_image
        imagePullPolicy: Never
        volumeMounts:
        - name: mysql-pvc
          mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-pvc
        persistentVolumeClaim:
         claimName: mysql-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: ipps
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-pv
spec:
    storageClassName: manual
    capacity:
      storage: 1Gi
    accessModes:
    - ReadWriteOnce
    hostPath:
      path: "/var/lib/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-pvc
spec:
    storageClassName: manual
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
