apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress_image
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: ipps
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - port: 5050
    targetPort: 5050
    name: wp
